apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: conprof
    app.kubernetes.io/version: vv0.1.0-dev
  name: conprof-governing-service
  namespace: observatorium
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app.kubernetes.io/name: conprof
