apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: observatorium-slos-production
spec:
  groups:
  - name: observatorium.slo.rules
    rules:
    - expr: |
        sum by (status_class) (
          label_replace(
            rate(http_requests_total{job="thanos-querier",namespace="telemeter-production"}[5m]
          ), "status_class", "${1}xx", "code", "([0-9])..")
        )
      labels:
        job: thanos-querier
        namespace: telemeter-production
      record: status_class:http_requests_total:rate5m
    - expr: |
        sum by (status_class) (
          label_replace(
            rate(http_requests_total{job="thanos-querier",namespace="telemeter-production"}[30m]
          ), "status_class", "${1}xx", "code", "([0-9])..")
        )
      labels:
        job: thanos-querier
        namespace: telemeter-production
      record: status_class:http_requests_total:rate30m
    - expr: |
        sum by (status_class) (
          label_replace(
            rate(http_requests_total{job="thanos-querier",namespace="telemeter-production"}[1h]
          ), "status_class", "${1}xx", "code", "([0-9])..")
        )
      labels:
        job: thanos-querier
        namespace: telemeter-production
      record: status_class:http_requests_total:rate1h
    - expr: |
        sum by (status_class) (
          label_replace(
            rate(http_requests_total{job="thanos-querier",namespace="telemeter-production"}[2h]
          ), "status_class", "${1}xx", "code", "([0-9])..")
        )
      labels:
        job: thanos-querier
        namespace: telemeter-production
      record: status_class:http_requests_total:rate2h
    - expr: |
        sum by (status_class) (
          label_replace(
            rate(http_requests_total{job="thanos-querier",namespace="telemeter-production"}[6h]
          ), "status_class", "${1}xx", "code", "([0-9])..")
        )
      labels:
        job: thanos-querier
        namespace: telemeter-production
      record: status_class:http_requests_total:rate6h
    - expr: |
        sum by (status_class) (
          label_replace(
            rate(http_requests_total{job="thanos-querier",namespace="telemeter-production"}[1d]
          ), "status_class", "${1}xx", "code", "([0-9])..")
        )
      labels:
        job: thanos-querier
        namespace: telemeter-production
      record: status_class:http_requests_total:rate1d
    - expr: |
        sum by (status_class) (
          label_replace(
            rate(http_requests_total{job="thanos-querier",namespace="telemeter-production"}[3d]
          ), "status_class", "${1}xx", "code", "([0-9])..")
        )
      labels:
        job: thanos-querier
        namespace: telemeter-production
      record: status_class:http_requests_total:rate3d
    - expr: |
        sum(status_class:http_requests_total:rate5m{job="thanos-querier",namespace="telemeter-production",status_class="5xx"})
        /
        sum(status_class:http_requests_total:rate5m{job="thanos-querier",namespace="telemeter-production"})
      labels:
        job: thanos-querier
        namespace: telemeter-production
      record: status_class_5xx:http_requests_total:ratio_rate5m
    - expr: |
        sum(status_class:http_requests_total:rate30m{job="thanos-querier",namespace="telemeter-production",status_class="5xx"})
        /
        sum(status_class:http_requests_total:rate30m{job="thanos-querier",namespace="telemeter-production"})
      labels:
        job: thanos-querier
        namespace: telemeter-production
      record: status_class_5xx:http_requests_total:ratio_rate30m
    - expr: |
        sum(status_class:http_requests_total:rate1h{job="thanos-querier",namespace="telemeter-production",status_class="5xx"})
        /
        sum(status_class:http_requests_total:rate1h{job="thanos-querier",namespace="telemeter-production"})
      labels:
        job: thanos-querier
        namespace: telemeter-production
      record: status_class_5xx:http_requests_total:ratio_rate1h
    - expr: |
        sum(status_class:http_requests_total:rate2h{job="thanos-querier",namespace="telemeter-production",status_class="5xx"})
        /
        sum(status_class:http_requests_total:rate2h{job="thanos-querier",namespace="telemeter-production"})
      labels:
        job: thanos-querier
        namespace: telemeter-production
      record: status_class_5xx:http_requests_total:ratio_rate2h
    - expr: |
        sum(status_class:http_requests_total:rate6h{job="thanos-querier",namespace="telemeter-production",status_class="5xx"})
        /
        sum(status_class:http_requests_total:rate6h{job="thanos-querier",namespace="telemeter-production"})
      labels:
        job: thanos-querier
        namespace: telemeter-production
      record: status_class_5xx:http_requests_total:ratio_rate6h
    - expr: |
        sum(status_class:http_requests_total:rate1d{job="thanos-querier",namespace="telemeter-production",status_class="5xx"})
        /
        sum(status_class:http_requests_total:rate1d{job="thanos-querier",namespace="telemeter-production"})
      labels:
        job: thanos-querier
        namespace: telemeter-production
      record: status_class_5xx:http_requests_total:ratio_rate1d
    - expr: |
        sum(status_class:http_requests_total:rate3d{job="thanos-querier",namespace="telemeter-production",status_class="5xx"})
        /
        sum(status_class:http_requests_total:rate3d{job="thanos-querier",namespace="telemeter-production"})
      labels:
        job: thanos-querier
        namespace: telemeter-production
      record: status_class_5xx:http_requests_total:ratio_rate3d
    - alert: ErrorBudgetBurn
      expr: |
        (
          status_class_5xx:http_requests_total:ratio_rate1h{job="thanos-querier",namespace="telemeter-production"} > (14.4*0.010000)
          and
          status_class_5xx:http_requests_total:ratio_rate5m{job="thanos-querier",namespace="telemeter-production"} > (14.4*0.010000)
        )
        or
        (
          status_class_5xx:http_requests_total:ratio_rate6h{job="thanos-querier",namespace="telemeter-production"} > (6*0.010000)
          and
          status_class_5xx:http_requests_total:ratio_rate30m{job="thanos-querier",namespace="telemeter-production"} > (6*0.010000)
        )
      labels:
        job: thanos-querier
        namespace: telemeter-production
        severity: info
    - alert: ErrorBudgetBurn
      expr: |
        (
          status_class_5xx:http_requests_total:ratio_rate1d{job="thanos-querier",namespace="telemeter-production"} > (3*0.010000)
          and
          status_class_5xx:http_requests_total:ratio_rate2h{job="thanos-querier",namespace="telemeter-production"} > (3*0.010000)
        )
        or
        (
          status_class_5xx:http_requests_total:ratio_rate3d{job="thanos-querier",namespace="telemeter-production"} > (0.010000)
          and
          status_class_5xx:http_requests_total:ratio_rate6h{job="thanos-querier",namespace="telemeter-production"} > (0.010000)
        )
      labels:
        job: thanos-querier
        namespace: telemeter-production
        severity: info
    - expr: |
        sum(label_replace(increase(http_requests_total{job="thanos-querier",namespace="telemeter-production"}[30d]), "status_class", "${1}xx", "code", "([0-9])..")) by (status_class)
      labels:
        job: thanos-querier
        namespace: telemeter-production
      record: status_class:http_requests_total:increase30d
    - expr: |
        (
          0.010000
        *
          sum(status_class:http_requests_total:increase30d)
        )
      labels:
        job: thanos-querier
        namespace: telemeter-production
      record: http_requests_total_errorbudget_requests
    - expr: |
        (
          sum(http_requests_total_errorbudget_requests{job="thanos-querier",namespace="telemeter-production"})
        -
          sum(status_class:http_requests_total:increase30d{job="thanos-querier",namespace="telemeter-production",status_class="5xx"})
        )
      labels:
        job: thanos-querier
        namespace: telemeter-production
      record: http_requests_total_errorbudget_remaining
    - expr: |
        (
          http_requests_total_errorbudget_remaining
        /
          http_requests_total_errorbudget_requests
        )
      labels:
        job: thanos-querier
        namespace: telemeter-production
      record: http_requests_total_errorbudget
